# Generated by Django 5.2.11 on 2026-02-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_score', models.FloatField()),
                ('topic_accuracy', models.FloatField()),
                ('attempts', models.PositiveIntegerField()),
                ('time_spent_sec', models.PositiveIntegerField()),
                ('actual_band', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
